server:
  port: 10804

spring:
  application:
    name: vagw

# TSP Device Admission Service configuration
tsp:
  device-admission:
    url: http://tsp-service:8080

feign:
  client:
    config:
      tsp-device-admission:
        connectTimeout: 500
        readTimeout: 500
        loggerLevel: basic
  circuitbreaker:
    enabled: true
